# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy React app to Azure Web App - Miracle-Translator-UI

on:
  push:
    branches:
      - master   # Trigger deploys on pushes to master branch
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Upload artifact (React build output)
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: ./build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write # Required for requesting the JWT
      contents: read  # Required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: react-build
          path: ./build

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6AC6D4D84846403594F48919F2A7C14A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_673F51DF0EF446C2900A85529BB639E2 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DF50B8C350D24568AEF3D2E241478ABC }}

      - name: Deploy React build to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'Miracle-Translator-UI'
          slot-name: 'Production'
          package: ./build

          

